"""empty message

Revision ID: 3dfe2cbe1a6d
Revises: f7f0b76118e7
Create Date: 2016-01-15 21:01:58.775000

"""

# revision identifiers, used by Alembic.
revision = '3dfe2cbe1a6d'
down_revision = 'f7f0b76118e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_filename', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image_filename')
    ### end Alembic commands ###
